
// login
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED'; 
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

//register
export const REGISTER_LOADING = 'REGISTER_LOADING';
export const R_NAME_CHANGED = 'R_NAME_CHANGED';
export const R_EMAIL_CHANGED = 'R_EMAIL_CHANGED';
export const R_PASSWORD_CHANGED = 'R_PASSWORD_CHANGED'; 
export const R_CONFIRM_PASSWORD_CHANGED = 'R_CONFIRM_PASSWORD_CHANGED';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

//App level
 export const USER_LOGGED_IN = 'USER_LOGGED_IN';
 export const USER_LOGOUT = 'USER_LOGOUT';
 export const USER_UPDATED = 'USER_UPDATED';
 export const CHANGE_LOCATION_SHARING_SETTING = 'CHANGE_LOCATION_SHARING_SETTING';

